Review Code
mhassa204/Code-Review pull request #1
Opened 2023-06-15 09:33 UTC by mhassa204

This branch is created for code review.

2023-06-15 14:16 UTC, mhassa204 reviewed
Hello Ali!

First of all, we want to congratulate all your work because it is good: 💯

But after the review, we have some good recommendations:

Please use a tag for a better semantic.
Please use external css, to ensure better practice in your CSS

Cheers, and Happy coding 🥇 👍

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> +  <body>
Please consider maintaining one closing head tag to ensure that you adhere to html semantic rules :blush: since duplicating the head is not a good practice and does not add meaning to your code :smirk:

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> -                </div>
Please consider using external css and avoid in-line styling :confused: since adding in-line css styling make your code complicated :stuck_out_tongue_winking_eye:

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> -                </div>
Please consider using external css and avoid in-line styling :angry: since adding in-line css styling make your code complicated :satisfied:

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> -                </div>
Please consider using external css and avoid in-line styling to make your code easier to read and understand :smiley:

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> -                </div>
Please consider using external css and avoid in-line styling :tired_face: to make your code easier to read and understand :smiley:

2023-06-15 14:16 UTC, mhassa204 commented on index.html
> -
Please consider using external css and avoid in-line styling :tired_face: to make your code easier to read and understand :blush:

2023-06-15 14:16 UTC, mhassa204 commented on style.css
> -    color: #fff !important;
Please consider removing !important :fearful:

2023-06-15 14:16 UTC, mhassa204 commented on style.css
> -    font-size: 20px;
Please consider removing !important and consider fixing .navbar .navbar-nav a :weary:

2023-06-15 14:16 UTC, mhassa204 commented on style.css
> -    background-color: black;
Please consider removing !important and consider fixing .navbar .navbar-nav a as you cannot use .navbar-nav inside .navbar :disappointed:

2023-06-15 14:28 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @mhassa204  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights :green_circle: 
- Good use of GitHub inline comments :fire: 

## Required Changes ♻️
- Great job so far @mhassa204  There are just a few changes I'll suggest. :wink: 
- [ ] I noticed that in your comments, you didn't always include an explanation, a `why`, for each requested change. :confused: 
- For example:
- **This is a well-explained request:** 
Why don't you use an article tag for the `.first-article `element instead of a `div`, that would improve the HTML structure and make the page more accessible :+1: 
- **This request lacks a "why":** 
Why don't you use an `article` tag here instead of a `div`?
- So kindly ensure that all your comments are accompanied by a valid `why` for those changes being requested :wink: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A
Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 16:21 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @mhassa204  , 

Your project is finally complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

## Highlights :fire:
- Good  use of GitHub Inline Comments feature :heavy_check_mark: 
- Comments are polite :heavy_check_mark: 
- Comments include a `why` :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 12:53 UTC, merged